### ISSUE TITLE
Proposed Analysis: Add batch correction module

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#10] opened 2021-05-17 19:22 UTC
#### What are the scientific goals of the analysis?
Add batch correction module to this [repo](https://github.com/PediatricOpenTargets/OpenPBTA-analysis)

#### What methods do you plan to use to accomplish the scientific goals?
Add batch correction with options for correction by library, sequencing center, dataset (eg TARGET, TCGA, GTEX) - Open to input for how you have been doing this in the past @komalsrathi  

#### What input data are required for this analysis?
RDS files

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
0.5-1 day - can work on now, but data will be available in v2

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@komalsrathi

**Comment by aadamk** [comment] 2021-05-19 13:09
From the OT meeting this morning, I'm informing on additional batch correction methods that would be valuable to include and benchmark in this module. The concern from today's meeting was that the cancer to GTEx batch correction may be shrinking cancer gene expression down to normal expression (hence hurting statistical power). 

Potential solutions to mitigate this effect may be in the following batch correction implementations:

1. RUVseq - vignette [here](https://bioconductor.riken.jp/packages/3.0/bioc/vignettes/RUVSeq/inst/doc/RUVSeq.pdf). Specifically RUVg, using a set of negative control genes to inform the batch correction. This will, however, require correction for compositional biases (e.g. EdgeR's TMM normalization or DESeq2's geometric mean based normalization) prior to running RUVg and evaluating the effects on density plots and UMAP output. The RUVseq vignette also provides information about implementation in the framework of DGE analysis with EdgeR (which will be a different workflow than for batch benchmarking evaluation).  
2. Evaluation of known and hidden factors using PEER - https://github.com/PMBio/peer/wiki/Tutorial

**Comment by komalsrathi** [comment] 2021-05-19 13:26
Thanks @aadamk sounds good to me. Do you want to chat about this (this week or next)? In the meanwhile I can go through the two linked manuals.

**Comment by komalsrathi** [comment] 2021-05-19 18:58
I have tried installing PEER through source and R - both are erroring out. Can you test if you can install the R package? If you are able to then it may have something to do with R v4.0.4.
> 2. Evaluation of known and hidden factors using PEER - https://github.com/PMBio/peer/wiki/Tutorial

**Comment by aadamk** [comment] 2021-05-19 19:14
I know GTEx has expected counts available (right?), which would be compatible with RUVseq + EdgeR. Is the same available for the TARGET dataset? 

I wasn't able to install PEER either, regardless of whether I attempted install from the R binary or building from source (I get a cryptic numpy error).

Not sure if PEER is still supported. There may be equivalent methods out there, and I can circle back and inform. RUVseq would be valuable if we can get uniformity in the quantitation type. @jharenza, do you know if expected or raw counts are available for TARGET data?

**Comment by komalsrathi** [comment] 2021-05-19 19:21
Yes but we are using TPM for a lot of downstream analysis - I am assuming we would want to correct those as well?

**Comment by aadamk** [comment] 2021-05-19 19:51
per slack discussion with @komalsrathi - expected counts are available for all datasets, making them appropriate for RUVseq + EdgeR. 

My thoughts: 
For batch evaluations, expected counts are the appropriate input and can be evaluated by UMAP before and after EdgeR + RUVseq analysis. 

Since TPM is important for visualizations for Open Targets, the batch-corrected TMM values from EdgeR + RUVseq pipeline can be converted to TPM using EdgeR functions from the following post under `Calculating TPM`: http://luisvalesilva.com/datasimple/rna-seq_units.html. 

These values could then be used for UMAP evaluations as well and any other downstream visualizations that may be necessary. 

Does this all sound reasonable @jharenza and @komalsrathi?

**Comment by jharenza** [comment] 2021-05-19 20:09
> @jharenza, do you know if expected or raw counts are available for TARGET data?

Just in scanning the DCC website, I see counts for some data and not others. (@yuankunzhu - do you know if the counts are available on GDC)? @afarrel do you have a count matrix for all of TARGET on isilon? If not, we can look at just TARGET NBL, for which we definitely have counts for on isilon or possibly box, since that dataset is being used as our proof of principle anyway.

>My thoughts:
For batch evaluations, expected counts are the appropriate input and can be evaluated by UMAP before and after EdgeR + RUVseq analysis.
>
>Since TPM is important for visualizations for Open Targets, the batch-corrected TMM values from EdgeR + RUVseq pipeline can be converted to TPM using EdgeR functions from the following post under Calculating TPM: http://luisvalesilva.com/datasimple/rna-seq_units.html.
>
>These values could then be used for UMAP evaluations as well and any other downstream visualizations that may be necessary.

This sounds good to me. Any other thoughts @yuankunzhu and @allisonheath ?  I am assuming every dataset would require normalization by library if we see this is needed, so we would forego RSEM TPM altogether.

**Comment by komalsrathi** [comment] 2021-05-19 20:12
@jharenza I have counts for TARGET, GTEx and TCGA from diseaseXpress (just need to put them together because they are in individual RSEM files). Because we are using TPM from diseaseXpress, I think we should both TPM and counts from the same source unless there is a reason you want to look at other sources.

**Comment by jharenza** [comment] 2021-05-19 20:20
> @jharenza I have counts for TARGET, GTEx and TCGA from diseaseXpress (just need to put them together because they are in individual RSEM files). Because we are using TPM from diseaseXpress, I think we should both TPM and counts from the same source unless there is a reason you want to look at other sources.

Oh great, this sounds good - yeah, let's use this for now.

**Comment by komalsrathi** [comment] 2021-05-20 13:12
> For batch evaluations, expected counts are the appropriate input and can be evaluated by UMAP before and after EdgeR + RUVseq analysis.
> 
> Since TPM is important for visualizations for Open Targets, the batch-corrected TMM values from EdgeR + RUVseq pipeline can be converted to TPM using EdgeR functions from the following post under `Calculating TPM`: http://luisvalesilva.com/datasimple/rna-seq_units.html.

@aadamk can you walk me through the steps again? we have worked on so many different tickets with differential expression - I am unsure where to start.

**Comment by aadamk** [comment] 2021-05-20 13:39
yes. 

Part A: For benchmarking batch correction performance, there are 3 possible approaches for batch correcting by stably expressed genes: 
1. Leverage the full housekeeping gene list [housekeeping transcript atlas](https://housekeeping.unicamp.br/?download).
2. Leverage the `most stable transcripts` list from the housekeeping atlas.
3. Run a first-pass DGE analysis using TMM normalization between cancer and normal using the full housekeeping gene list. Retain non-significantly altered genes as the negative control gene set for downstream batch correction. 

Part B: The actual batch correction algorithm would then look like: 
1. Given the optimal method from above, take expected counts and TMM normalize.
2. Take the TMM normalized values and run RUVseq batch correction. 
3. Verify uniformity of the expression by density plots, `plotRLE`, and `plotPCA` from RUVseq. 
4. UMAP analyses in housekeeping and full transcriptome spaces from expected counts that have been TMM and RUV-seq corrected (from Part B steps 1-2). 
5. Compute TPM from EdgeR's functions (http://luisvalesilva.com/datasimple/rna-seq_units.html) on the output of step2. 
6. UMAP analyses in housekeeping and full transcriptome spaces on TPM's computed from step 5. 

This is the way I'm thinking about this at the moment (will likely require a separate ticket). We're still discussing approaches to Part A, Step 3 on the Openpbta-modules channel on slack - will update once everything is confirmed and everyone is on the same page.

**Comment by komalsrathi** [comment] 2021-05-20 13:43
Thank you Adam, this is super helpful. I will start putting together the scripts.

**Comment by jharenza** [comment] 2021-05-20 14:22
@komalsrathi I haven't had a chance to look at this, but it sounds like we may want to break this up into a staggered PR to keep each one focused on one aspect and to make review easier.

**Comment by komalsrathi** [comment] 2021-05-20 15:47
@jharenza Yes, correct me if I am wrong - from our slack discussion, Yuanchao will be doing Part A. In the meanwhile, I will just start drafting a script for Part B.

**Comment by jharenza** [comment] 2021-05-25 21:36
> * Leverage the full housekeeping gene list [housekeeping transcript atlas](https://housekeeping.unicamp.br/?download).
> * Leverage the `most stable transcripts` list from the housekeeping atlas.
> * Run a first-pass DGE analysis using TMM normalization between cancer and normal using the full housekeeping gene list. Retain non-significantly altered genes as the negative control gene set for downstream batch correction.

@aadamk for this, what is the difference between 2 and 3? I am going to break up this ticket. So I understand, step 1 would be for @komalsrathi to run all HK genes in the batch correction and step 2/3 would be to run only stably expressed genes, as determined by DE between NBL and normal? Or were thinking of assessing step 2 in an additional way (looking at expression across samples via something like z-score and selecting top N most stable? Thanks!

**Comment by aadamk** [comment] 2021-05-26 11:57
> > * Leverage the full housekeeping gene list [housekeeping transcript atlas](https://housekeeping.unicamp.br/?download).
> > * Leverage the `most stable transcripts` list from the housekeeping atlas.
> > * Run a first-pass DGE analysis using TMM normalization between cancer and normal using the full housekeeping gene list. Retain non-significantly altered genes as the negative control gene set for downstream batch correction.
> 
> @aadamk for this, what is the difference between 2 and 3? I am going to break up this ticket. So I understand, step 1 would be for @komalsrathi to run all HK genes in the batch correction and step 2/3 would be to run only stably expressed genes, as determined by DE between NBL and normal? Or were thinking of assessing step 2 in an additional way (looking at expression across samples via something like z-score and selecting top N most stable? Thanks!

2 is actually distinct from 3. For 2, I was referring to the downloadable list from HTA from the link above (the most stable set of 20 transcripts that they identified from their work), whereas 3 is the empirically defined set of negative control genes from first pass DE of the full HTA list.

**Comment by jharenza** [comment] 2021-05-26 12:33
>2 is actually distinct from 3. For 2, I was referring to the downloadable list from HTA from the link above (the most stable set of 20 transcripts that they identified from their work), whereas 3 is the empirically defined set of negative control genes from first pass DE of the full HTA list.

Ok, got it, thanks. I will find and post those 20 transcripts in the new ticket.

**Comment by aadamk** [comment] 2022-01-19 14:06
Closing to focus on NBL use case. Feel free to re-open if needed.

**Closed by aadamk** 2022-01-19 14:06 UTC
Labels: low priority
