### ISSUE TITLE
Copy TARGET DNA and RNA fastq files from isilon to CAVATICA

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#49] opened 2021-06-22 12:54 UTC
#### What data file(s) does this issue pertain to?
Copying TARGET DNA (WXS/Panel) fastq files and RNA fastq files from Isilon to CAVATICA

#### What needs to be done?

@afarrel to uncompress/copy files to Maris folder and give path to @yuankunzhu @jharenza and @komalsrathi . @yuankunzhu or @komalsrathi to copy files to Cavatica

#### Put your question or report your issue here.
Will add manifests and paths here.

**Comment by komalsrathi** [comment] 2021-06-22 15:01
I was testing the command line uploader `sb` but can't get it to work: https://docs.sevenbridges.com/docs/general-commands - not sure what the issue is because I am configuring using sb configure with my auth token. Have contacted sb genomics. @yuankunzhu any other "easy" way to upload files or who can help me debug the `sb` issue?

**Comment by yuankunzhu** [comment] 2021-06-22 16:55
> I was testing the command line uploader `sb` but can't get it to work: https://docs.sevenbridges.com/docs/general-commands - not sure what the issue is because I am configuring using sb configure with my auth token. Have contacted sb genomics. @yuankunzhu any other "easy" way to upload files or who can help me debug the `sb` issue?

Hi @komalsrathi what error did you get. Good to know you are using your auth token, and you also need to make sure the api endpoint is `https://cavatica-api.sbgenomics.com/v2`

**Comment by komalsrathi** [comment] 2021-06-22 17:00
from our slack discussion, changed the endpoint and it works now. Thanks @yuankunzhu !!

**Comment by jharenza** [comment] 2021-06-22 22:11
destination folder: `https://cavatica.sbgenomics.com/u/yuankun/test-target`

**Comment by komalsrathi** [comment] 2021-06-24 15:25
I have started the upload of `/mnt/isilon/maris_lab/target_nbl_ngs/Open_Targets/TARGET_DNA/TARGET_Capture_Panel` under https://cavatica.sbgenomics.com/u/yuankun/test-target/files/#q?path=TARGET_Capture_Panel

**Comment by afarrel** [comment] 2021-06-29 05:20
[SRR_TARGET_Capture_NBL_Manifest.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6730838/SRR_TARGET_Capture_NBL_Manifest.txt)
[SRR_TARGET_WXS_AML_Manifest.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6730839/SRR_TARGET_WXS_AML_Manifest.txt)
[SRR_TARGET_WXS_NBL_Manifest.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6730840/SRR_TARGET_WXS_NBL_Manifest.txt)

@yuankunzhu @zhangb1 @jharenza  Here are the SRR to TARGET USI manifests for the WXS and Capture data transferred to CAVATICA

**Comment by jharenza** [comment] 2021-06-29 13:02
Thank you @afarrel

**Comment by zhangb1** [comment] 2021-06-30 12:02
> [SRR_TARGET_Capture_NBL_Manifest.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6730838/SRR_TARGET_Capture_NBL_Manifest.txt)
> [SRR_TARGET_WXS_AML_Manifest.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6730839/SRR_TARGET_WXS_AML_Manifest.txt)
> [SRR_TARGET_WXS_NBL_Manifest.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6730840/SRR_TARGET_WXS_NBL_Manifest.txt)
> 
> @yuankunzhu @zhangb1 @jharenza Here are the SRR to TARGET USI manifests for the WXS and Capture data transferred to CAVATICA

Did you upload the WXS data to cavatica? I didn't see them  https://cavatica.sbgenomics.com/u/yuankun/test-target/files/#q ,did you create the folder for that?

**Comment by komalsrathi** [comment] 2021-07-01 15:42
@zhangb1 I only uploaded the capture panel - that's all I was asked for.

**Comment by jharenza** [comment] 2021-07-08 20:31
closing since we now have GDC access

**Closed by jharenza** 2021-07-08 20:31 UTC
Labels: bix-ops, next-data-release
