### ISSUE TITLE
Update Analysis: Generate consensus_seg_annotated_cn_[autosomes|x_any_y].tsv.gz 

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#159] opened 2021-08-11 21:18 UTC
#### What analysis module should be updated and why?
We need to rerun annotation because WGS consensus seg was updated and available in [dev](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/copy_number_consensus_call/results/pbta-cnv-consensus.seg.gz) we will annotate the CNV region if it overlaps with a gene region. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Just a rerun of focal-cn-file-preparation module as below:

 `bash analyses/focal-cn-file-preparation/run-prepare-cn-OpenTarget.sh`
 
#### What input data should be used? Which data were used in the version being updated?
**v8**
histologies.tsv
analyses/copy_number_consensus_call/results/cnv-consensus.seg.gz

**Comment by zhangb1** [comment] 2021-08-13 18:22
seems the GMKF germline gender also missing in the histology file for the WGS data.

I can add that

**Comment by jharenza** [comment] 2021-08-13 22:42
> seems the GMKF germline gender also missing in the histology file for the WGS data.
> 
> 
> 
> I can add that 

Cc @ewafula - @zhangb1 if you have this, can you attach to this ticket? Thanks!

**Comment by ewafula** [comment] 2021-08-14 05:26
@

> > seems the GMKF germline gender also missing in the histology file for the WGS data.
> > I can add that
> 
> Cc @ewafula - @zhangb1 if you have this, can you attach to this ticket? Thanks!

@zhangb1, even if you did update it on your end, can you attach it for me here to update with other v8/histologies.tsv updates.

**Comment by zhangb1** [comment] 2021-08-14 12:35
[GMKF_germline_gender_est.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6986471/GMKF_germline_gender_est.txt)

@ewafula

**Comment by zhangb1** [comment] 2021-08-16 13:27
@jharenza 

when running the `focal-cn-file-preparation` for PBTA and GMKF WGS . there is an error, seem there is the gene_symbol mapping issue between with the gene_id? 

```
Error: Problem with `mutate()` input `gene_symbol`.
✖ mapIds must have at least one key to match against.
ℹ Input `gene_symbol` is `AnnotationDbi::mapIds(...)`.
Backtrace:
     █
  1. ├─`%>%`(...)
  2. ├─dplyr::mutate(...)
  3. ├─global::process_annotate_overlaps(cnv_df = cnv_no_xy, txdb_exons = tx_exons)
  4. │ ├─BiocGenerics::lapply(...)
  5. │ └─base::lapply(...)
  6. │   └─FUN(X[[i]], ...)
  7. │     └─`%>%`(...)
  8. ├─dplyr::mutate(...)
  9. ├─dplyr:::mutate.data.frame(...)
 10. │ └─dplyr:::mutate_cols(.data, ...)
 11. │   ├─base::withCallingHandlers(...)
 12. │   └─mask$eval_all_mutate(quo)
 13. ├─AnnotationDbi::mapIds(...)
 14. ├─AnnotationDbi::mapIds(...)
 15. │ └─AnnotationDbi::mapIds_base(x, keys, column, keytype, ..., multiVals = multiVals)
 16. │   └─base::stop(wmsg("mapIds must have at least one key to match against."))
 17. └─base::.handleSimpleError(...)
 18.   └─dplyr:::h(simpleError(msg, call))
Execution halted
```

not sure who can help ?

**Comment by jharenza** [comment] 2021-08-16 13:50
@runjin326 can you look into this for @zhangb1

**Comment by zhangb1** [comment] 2021-08-16 13:59
```
Rscript --vanilla 04-prepare-cn-file.R --cnv_file ../../scratch/consensus_seg_with_status.tsv --gtf_file ../../data/gencode.v27.primary_assembly.annotation.gtf.gz --metadata ../../data/histologies.tsv --filename_lead "consensus_seg_annotated_cn" --seg
```

I use the  OT dev.  repo code. 

The inputs for the command is here : 
[consensus_seg_with_status.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/6992867/consensus_seg_with_status.tsv.zip)
[histologies.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/6992877/histologies.tsv.zip)
please unzip the file before running the command

**Comment by runjin326** [comment] 2021-08-16 14:01
@zhangb1, thanks. I will look into this and let you know what the issue is - or what fix it needs.

**Comment by runjin326** [comment] 2021-08-16 15:00
@zhangb1, @jharenza, ok I figured out what the issue is - so originally we handled all the specimens in the same DataFrame for mapping using `AnnotationDbi::mapIds`. During last update, due to RAM issues, I modified the code to do the mapping per sample. That generates an issue since for some samples, e.g., `BS_1EQGGHHQ`, none of the transcript ENSEMBLE ID in `ensembl` column has a mapped gene symbol in `AnnotationDbi::mapIds` database. Since now @zhangb1 will be running it (so less likely with RAM issues) - I removed the piece that iterate through each sample - and the issue was fixed. So @zhangb1, if you replace the function `process_annotate_overlaps` with the following: 
```
process_annotate_overlaps <- function(cnv_df,
                                      txdb_exons,
                                      filt_na_symbol = TRUE) {
  # This function takes a standardized data.frame that contains genomic range
  # information and finds the overlaps with a TxDb object. It will discard
  # Ensembl gene IDs with no gene symbol by default.
  #
  # Args:
  #   cnv_df: standardized data.frame that contains the segments used in the
  #           CNV caller
  #   txdb_exons: exons to be merged with the CNV data.frame; output of
  #               GenomicFeatures::exons
  #   filt_na_symbol: logical, if TRUE, rows without gene symbols will be
  #                   removed; default is TRUE
  #
  # Returns:
  #   A data.frame with the following columns:
  #     biospecimen_id, status, copy_number, ploidy, ensembl, gene_symbol,
  #     cytoband
  

  # make it into GRanges 
  cnv_gr <- cnv_df %>%
    GenomicRanges::makeGRangesFromDataFrame(keep.extra.columns = TRUE,
                                            starts.in.df.are.0based = FALSE)
  
  # Create a data.frame with the overlaps between the CNV file and hg38 genome
  # annotations
  overlaps <- IRanges::mergeByOverlaps(cnv_gr, txdb_exons)
  
  # Create a data.frame with selected columns from the `autosome_overlaps`
  # object
  annotated_cn <- data.frame(
    biospecimen_id = overlaps$Kids_First_Biospecimen_ID,
    status = overlaps$status,
    copy_number = overlaps$copy_number,
    ploidy = overlaps$tumor_ploidy,
    ensembl = unlist(overlaps$gene_id),
    stringsAsFactors = FALSE
  ) %>%
    dplyr::distinct() %>%
    # Discard the gene version information in order to get gene symbols and
    # cytoband mappings
    dplyr::mutate(ensembl = gsub("\\..*", "", ensembl))
  
  annotated_cn <- annotated_cn %>%
    dplyr::mutate(
      gene_symbol = AnnotationDbi::mapIds(org.Hs.eg.db::org.Hs.eg.db,
                                          keys = ensembl,
                                          column = "SYMBOL",
                                          keytype = "ENSEMBL"),
      cytoband = AnnotationDbi::mapIds(org.Hs.eg.db::org.Hs.eg.db,
                                       keys = ensembl,
                                       column = "MAP",
                                       keytype = "ENSEMBL")
    )
  
  # drop rows that have NA values for the gene symbol
  if (filt_na_symbol) {
    annotated_cn <- annotated_cn %>%
      dplyr::filter(!is.na(gene_symbol))
  }
  return(annotated_cn)
}

```
It should be fine. 
I have tested already and it works.

**Comment by zhangb1** [comment] 2021-08-16 17:10
Thanks @runjin326 . I can got the results now. Are we going to use per sample or not in the future?  we need to implement the code to our CWL too.  it will be having the same error using the per sample code.  

cc ^ @jharenza

**Comment by runjin326** [comment] 2021-08-16 17:12
@zhangb1, I think we don't need to keep the per sample code in the future. It was implemented before only because  sometimes it gets killed due to my local RAM - but now that this would no longer be an issue, we can just keep running it as a batch.

**Comment by zhangb1** [comment] 2021-08-16 17:14
@runjin326  can you merge the code to the OT dev or the master? so when we git the code will be the latest one.

**Comment by runjin326** [comment] 2021-08-16 17:16
@zhangb1, I don't have merge privilege but maybe once you are done with generating the files, you can open a PR and assign me and @jharenza as reviewers and if everything looks good, @jharenza can merge it?

**Comment by zhangb1** [comment] 2021-08-16 17:19
@runjin326 I think you may need to open an PR. since you will change the code?  if I am not mistaken.

**Comment by runjin326** [comment] 2021-08-16 17:20
@zhangb1, ok I will!

**Comment by zhangb1** [comment] 2021-08-16 19:56
This work has been done , the code works , I think we can close this ticket

**Closed by zhangb1** 2021-08-16 19:56 UTC
Labels: next-data-release, bix-ops, CNV
